name: Pull the app and deploy to EKS

on:
  workflow_dispatch:
#  push:
#  branches: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bitirmeodevi_backend:latest ./react-express-mongodb/backend
          docker push ${{ secrets.DOCKER_USERNAME }}/bitirmeodevi_backend:latest
      
      - name: Build and Push Frontend Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bitirmeodevi_frontend:latest ./react-express-mongodb/frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/bitirmeodevi_frontend:latest